import telebot
from telebot import types

bot = telebot.TeleBot('')

@bot.message_handler(commands=['start'])
def start_bot(message):
    bot.send_message(message.from_user.id, "Здравствуйте! Я бот программы «Движение вверх»,\nраздел «Одаренные дети», могу помочь Вам построить индивидуальную развивающую траекторию по различным направлениям.")
    
    # Создаем клавиатуру
    keyboard = types.InlineKeyboardMarkup()
    
    key_option = types.InlineKeyboardButton(text='Выбрать категории', callback_data='starter')
    
    keyboard.add(key_option)
    
    bot.send_message(message.chat.id, text="Для начала работы нажмите на кнопку", reply_markup=keyboard)

@bot.callback_query_handler(func=lambda call: True)
def callback_worker(call):
    if call.data == "starter":
        keyboard = types.InlineKeyboardMarkup()
        key_option1 = types.InlineKeyboardButton(text='Физика', callback_data='physics')
        key_option2 = types.InlineKeyboardButton(text='Информатика', callback_data='informatics')
        key_option3 = types.InlineKeyboardButton(text='Математика', callback_data='mathematics')
        key_option4 = types.InlineKeyboardButton(text='Биология, химия', callback_data='biology')
        key_option5 = types.InlineKeyboardButton(text='Английский язык', callback_data='english')
        key_option6 = types.InlineKeyboardButton(text='Русский язык, литература', callback_data='russian')
        key_option7 = types.InlineKeyboardButton(text='История, обществознание, право', callback_data='history')
        key_option8 = types.InlineKeyboardButton(text='Художественное творчество', callback_data='art')
        
        keyboard.add(key_option1)
        keyboard.add(key_option2)
        keyboard.add(key_option3)
        keyboard.add(key_option4)
        keyboard.add(key_option5)
        keyboard.add(key_option6)
        keyboard.add(key_option7)
        keyboard.add(key_option8)
        
        bot.send_message(call.message.chat.id, text="Выберите одно из направлений:", reply_markup=keyboard)
    elif call.data == "physics":
        keyboard = types.InlineKeyboardMarkup()
        sub_key1 = types.InlineKeyboardButton(text='Олимпиады', callback_data='olympiads_phisics')
        sub_key2 = types.InlineKeyboardButton(text='Конкурсы', callback_data='contests_phisics')
        sub_key3 = types.InlineKeyboardButton(text='Профильные лагеря', callback_data='camp_phisics')
        back_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='starter')
        
        keyboard.add(sub_key1)
        keyboard.add(sub_key2)
        keyboard.add(sub_key3)
        keyboard.add(back_key)
        
        bot.send_message(call.message.chat.id, "Выбрано направление Физика", reply_markup=keyboard)
    elif call.data == "informatics":
        keyboard = types.InlineKeyboardMarkup()
        sub_key1 = types.InlineKeyboardButton(text='Олимпиады', callback_data='olympiads_informatics')
        sub_key2 = types.InlineKeyboardButton(text='Конкурсы', callback_data='contests_informatics')
        sub_key3 = types.InlineKeyboardButton(text='Профильные лагеря', callback_data='camp_informatics')
        back_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='starter')
        
        keyboard.add(sub_key1)
        keyboard.add(sub_key2)
        keyboard.add(sub_key3)
        keyboard.add(back_key)
        
        bot.send_message(call.message.chat.id, "Выбрано направление Информатика", reply_markup=keyboard)
    elif call.data == "mathematics":
        keyboard = types.InlineKeyboardMarkup()
        sub_key1 = types.InlineKeyboardButton(text='Олимпиады', callback_data='olympiads_mathematics')
        sub_key2 = types.InlineKeyboardButton(text='Конкурсы', callback_data='contests_mathematics')
        sub_key3 = types.InlineKeyboardButton(text='Профильные лагеря', callback_data='camp_mathematics')
        back_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='starter')
        
        keyboard.add(sub_key1)
        keyboard.add(sub_key2)
        keyboard.add(sub_key3)
        keyboard.add(back_key)
        
        bot.send_message(call.message.chat.id, "Выбрано направление математика", reply_markup=keyboard)
    elif call.data == "biology":
        keyboard = types.InlineKeyboardMarkup()
        sub_key1 = types.InlineKeyboardButton(text='Олимпиады', callback_data='olympiads_biology')
        sub_key2 = types.InlineKeyboardButton(text='Конкурсы', callback_data='contests_biology')
        sub_key3 = types.InlineKeyboardButton(text='Профильные лагеря', callback_data='camp_biology')
        back_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='starter')
        
        keyboard.add(sub_key1)
        keyboard.add(sub_key2)
        keyboard.add(sub_key3)
        keyboard.add(back_key)
        
        bot.send_message(call.message.chat.id, "Выбрано направление биология, химия", reply_markup=keyboard)
    elif call.data == "english":
        keyboard = types.InlineKeyboardMarkup()
        sub_key1 = types.InlineKeyboardButton(text='Олимпиады', callback_data='olympiads_english')
        sub_key2 = types.InlineKeyboardButton(text='Конкурсы', callback_data='contests_english')
        sub_key3 = types.InlineKeyboardButton(text='Профильные лагеря', callback_data='camp_english')
        back_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='starter')
        
        keyboard.add(sub_key1)
        keyboard.add(sub_key2)
        keyboard.add(sub_key3)
        keyboard.add(back_key)
        
        bot.send_message(call.message.chat.id, "Выбрано направление английский язык", reply_markup=keyboard)
    elif call.data == "russian":
        keyboard = types.InlineKeyboardMarkup()
        sub_key1 = types.InlineKeyboardButton(text='Олимпиады', callback_data='olympiads_russian')
        sub_key2 = types.InlineKeyboardButton(text='Конкурсы', callback_data='contests_russian')
        sub_key3 = types.InlineKeyboardButton(text='Профильные лагеря', callback_data='camp_russian')
        back_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='starter')
        
        keyboard.add(sub_key1)
        keyboard.add(sub_key2)
        keyboard.add(sub_key3)
        keyboard.add(back_key)
        
        bot.send_message(call.message.chat.id, "Выбрано направление русский язык, литература", reply_markup=keyboard)
    elif call.data == "history":
        keyboard = types.InlineKeyboardMarkup()
        sub_key1 = types.InlineKeyboardButton(text='Олимпиады', callback_data='olympiads_history')
        sub_key2 = types.InlineKeyboardButton(text='Конкурсы', callback_data='contests_history')
        sub_key3 = types.InlineKeyboardButton(text='Профильные лагеря', callback_data='camp_history')
        back_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='starter')
        
        keyboard.add(sub_key1)
        keyboard.add(sub_key2)
        keyboard.add(sub_key3)
        keyboard.add(back_key)
        
        bot.send_message(call.message.chat.id, "Выбрано направление история, обществознание, право", reply_markup=keyboard)
    elif call.data == "art":
        keyboard = types.InlineKeyboardMarkup()
        sub_key1 = types.InlineKeyboardButton(text='Олимпиады', callback_data='olympiads_art')
        sub_key2 = types.InlineKeyboardButton(text='Конкурсы', callback_data='contests_art')
        sub_key3 = types.InlineKeyboardButton(text='Профильные лагеря', callback_data='camp_art')
        back_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='starter')
        
        keyboard.add(sub_key1)
        keyboard.add(sub_key2)
        keyboard.add(sub_key3)
        keyboard.add(back_key)
        
        bot.send_message(call.message.chat.id, "Выбрано направление художественное творчество", reply_markup=keyboard)
    elif call.data == "olympiads_phisics":
        keyboard = types.InlineKeyboardMarkup()
        url_button_1 = types.InlineKeyboardButton(text="Перечневые олимпиады по физике", url="https://postupi.online/olimp-list/?fsubject=6&amp;flevel=5&amp;ysclid=lxiu6dtb6p435656839")
        url_button_2 = types.InlineKeyboardButton(text="Международная олимпиада молодежи (ВШЭ)", url="https://olymp.hse.ru/inter/about_inter#about")
        url_button_3 = types.InlineKeyboardButton(text="Олимпиада школьников «Океан знаний»", url="https://www.kp.ru/edu/shkola/olimpiada-shkolnikov-okean-znanij/")
        url_button_4 = types.InlineKeyboardButton(text="Всероссийская олимпиада школьников", url="https://siriusolymp.ru/rules")
        url_button_5 = types.InlineKeyboardButton(text="Национальная технологическая олимпиада", url="https://ntcontest.ru/?ysclid=lxiui6rr6f758248545")
        url_button_6 = types.InlineKeyboardButton(text="Олимпиада школьников «Наследники Левши»", url="https://abitur71.tsu.tula.ru/olimp/?ysclid=lxiuk6142u190228195")
        url_button_7 = types.InlineKeyboardButton(text="Олимпиада «Росатом» по физике", url="https://postupi.online/olimpiada/olimpiada-rosatom-fizika/")
        sub_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='physics')
        
        keyboard.add(url_button_1)
        keyboard.add(url_button_2)
        keyboard.add(url_button_3)
        keyboard.add(url_button_4)
        keyboard.add(url_button_5)
        keyboard.add(url_button_6)
        keyboard.add(url_button_7)
        keyboard.add(sub_key)
        
        bot.send_message(call.message.chat.id, "Отлично! Обязательно пробуй свои силы! Могу порекомендовать Вам следующие олимпиады по физике:", reply_markup=keyboard)
    elif call.data == "contests_phisics":
        keyboard = types.InlineKeyboardMarkup()
        url_button_1 = types.InlineKeyboardButton(text="Конкурс исследовательских и проектных работ школьников «Высший пилотаж»", url="https://olymp.hse.ru/projects/physics-avangard")
        url_button_2 = types.InlineKeyboardButton(text="Тульский открытый чемпионат знаний, инициатив, проектов «Энергия будущих поколенийв интересах устойчивого развития региона»", url="http://www.doobr71.ru/konkursy-i-meropriyatiya/")
        url_button_3 = types.InlineKeyboardButton(text="Всероссийский конкурс научно-технологических проектов «Большие вызовы»", url="https://konkurs.sochisirius.ru/regions/71")
        url_button_4 = types.InlineKeyboardButton(text="Всероссийский конкурс «Большая перемена»", url="https://vsekonkursy.ru/bolshaya-peremena-2024.html")
        url_button_5 = types.InlineKeyboardButton(text="Всероссийские конкурсы ССИТ", url="https://konkurs.sertification.org/new_store/mathematics.htm")
        sub_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='physics')
        
        keyboard.add(url_button_1)
        keyboard.add(url_button_2)
        keyboard.add(url_button_3)
        keyboard.add(url_button_4)
        keyboard.add(url_button_5)
        keyboard.add(sub_key)
        
        bot.send_message(call.message.chat.id, "Отлично! Обязательно пробуй свои силы! Могу порекомендовать Вам следующие конкурсы по физике:", reply_markup=keyboard)
    elif call.data == "camp_phisics":
        keyboard = types.InlineKeyboardMarkup()
        url_button_1 = types.InlineKeyboardButton(text="Физико-математические лагеря для подростков", url="https://vlagere.ru/camps/physical-math/teenagers/?ysclid=lxiw7wv1oj220296294")
        url_button_2 = types.InlineKeyboardButton(text="Летняя школа МФТИ", url="https://leto.kmipt.ru/")
        url_button_3 = types.InlineKeyboardButton(text="Выездные школы НИУ ВШЭ", url="https://olimpiada.ru/activity/5569")
        url_button_4 = types.InlineKeyboardButton(text="Летняя олимпиадная школа МИФИ", url="https://olymp.mephi.ru/olympiad/577")
        url_button_5 = types.InlineKeyboardButton(text="Областной профильный лагерь «Летняя многопрофильная школа»", url="https://тоцдод.рф/областной-профильный-лагерь-лмш/?ysclid=lxiwknjwbj870392740")
        sub_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='physics')
        
        keyboard.add(url_button_1)
        keyboard.add(url_button_2)
        keyboard.add(url_button_3)
        keyboard.add(url_button_4)
        keyboard.add(url_button_5)
        keyboard.add(sub_key)
        
        bot.send_message(call.message.chat.id, "Отлично! Обязательно пробуй свои силы! Могу порекомендовать Вам следующие профильные лагеря по физике:", reply_markup=keyboard)
    elif call.data == "olympiads_informatics":
        keyboard = types.InlineKeyboardMarkup()
        url_button_1 = types.InlineKeyboardButton(text="Всероссийская олимпиада школьников", url="https://siriusolymp.ru/rules")
        url_button_2 = types.InlineKeyboardButton(text="Национальная технологическая олимпиада", url="https://ntcontest.ru/?ysclid=lxiui6rr6f758248545")
        url_button_3 = types.InlineKeyboardButton(text="Перечневые олимпиады по информатике", url="https://postupi.online/olimp-list/?fsubject=49&amp;flevel=5")
        url_button_4 = types.InlineKeyboardButton(text="Командная олимпиада по программированию (ВШЭ)", url="https://olymp.hse.ru/coding/")
        url_button_5 = types.InlineKeyboardButton(text="Всероссийская Толстовская олимпиада школьников по информатике", url="https://olymp.tsput.ru/lp/")
        url_button_6 = types.InlineKeyboardButton(text="Олимпиада по информатике от Яндекс учебника", url="https://education.yandex.ru/olymp/inf2024/")
        url_button_7 = types.InlineKeyboardButton(text="Всероссийская олимпиада по искусственному интеллекту", url="https://ai.edu.gov.ru/")
        url_button_8 = types.InlineKeyboardButton(text="Всероссийская олимпиада школьников", url="https://siriusolymp.ru/rules")
        url_button_9 = types.InlineKeyboardButton(text="Олимпиада «Фоксфорд» по информатике", url="https://olymp.foxford.ru/?ysclid=lxk3o6abtf945613642")
        sub_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='informatics')
        
        keyboard.add(url_button_1)
        keyboard.add(url_button_2)
        keyboard.add(url_button_3)
        keyboard.add(url_button_4)
        keyboard.add(url_button_5)
        keyboard.add(url_button_6)
        keyboard.add(url_button_7)
        keyboard.add(url_button_8)
        keyboard.add(url_button_9)
        keyboard.add(sub_key)
        
        bot.send_message(call.message.chat.id, "Отлично! Обязательно пробуй свои силы! Могу порекомендовать Вам следующие олимпиады по информатике:", reply_markup=keyboard)
    elif call.data == "contests_informatics":
        keyboard = types.InlineKeyboardMarkup()
        url_button_1 = types.InlineKeyboardButton(text="Областной конкурс «Компьютерный мир»", url="https://тоцдод.рф/blog/2023/01/27/областной-конкурс-компьютерный-мир/?ysclid=lxiz7pu150815316117")
        url_button_2 = types.InlineKeyboardButton(text="Всероссийский конкурс «Мир информатики»", url="https://радуга-талантов.рф/конкурс-школа-мир-информатики/")
        url_button_3 = types.InlineKeyboardButton(text="Международный конкурс по информатике «Инфознайка»", url="https://www.infoznaika.ru/")
        url_button_4 = types.InlineKeyboardButton(text="Всероссийский творческий конкурс по информатике «Пиксель»", url="http://www.vrofuture.ru/konkurs-po-informatike-piksel/?ysclid=lxk0ljana6272398010")
        url_button_5 = types.InlineKeyboardButton(text="Всероссийский конкурс «КИТ – компьютеры, информатика, технологии»", url="https://konkurskit.ru/")
        url_button_6 = types.InlineKeyboardButton(text="Всероссийские конкурсы ССИТ", url="https://konkurs.sertification.org/new_store/mathematics.htm")
        sub_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='informatics')
        
        keyboard.add(url_button_1)
        keyboard.add(url_button_2)
        keyboard.add(url_button_3)
        keyboard.add(url_button_4)
        keyboard.add(url_button_5)
        keyboard.add(url_button_6)
        keyboard.add(sub_key)
        
        bot.send_message(call.message.chat.id, "Отлично! Обязательно пробуй свои силы! Могу порекомендовать Вам следующие конкурсы по информатике:", reply_markup=keyboard)
    elif call.data == "camp_informatics":
        keyboard = types.InlineKeyboardMarkup()
        url_button_1 = types.InlineKeyboardButton(text="Летняя школа спортивного программирования ТулГУ", url="https://vk.com/tsu.tula.icpc")
        url_button_2 = types.InlineKeyboardButton(text="Программа «Код будущего»", url="https://www.gosuslugi.ru/futurecode?view=online")
        url_button_3 = types.InlineKeyboardButton(text="Обучение в Яндекс Лицее", url="https://lyceum.yandex.ru/")
        url_button_4 = types.InlineKeyboardButton(text="Курс «Профессия - разработчик»", url="https://skillbox.ru/course/profession-developer-trial/")
        url_button_5 = types.InlineKeyboardButton(text="Бесплатные курсы по программированию", url="https://stepik.org/catalog/246?difficulty=easy&amp;free=true")
        url_button_6 = types.InlineKeyboardButton(text="Детские ИТ-лагеря", url="https://journal.tinkoff.ru/list/it-summer-camps/?ysclid=lxk1dvu63u899266629")
        url_button_7 = types.InlineKeyboardButton(text="Образовательная программа «Информатика. Регионы»", url="https://sochisirius.ru/obuchenie/nauka/smena1551/7219")
        url_button_8 = types.InlineKeyboardButton(text="Областной профильный лагерь «Летняя многопрофильная школа»", url="https://тоцдод.рф/областной-профильный-лагерь-лмш/?ysclid=lxiwknjwbj870392740")
        sub_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='informatics')
        
        keyboard.add(url_button_1)
        keyboard.add(url_button_2)
        keyboard.add(url_button_3)
        keyboard.add(url_button_4)
        keyboard.add(url_button_5)
        keyboard.add(url_button_6)
        keyboard.add(url_button_7)
        keyboard.add(url_button_8)
        keyboard.add(sub_key)
        
        bot.send_message(call.message.chat.id, "Отлично! Обязательно пробуй свои силы! Могу порекомендовать Вам следующие курсы и профильные лагеря по информатике:", reply_markup=keyboard)
    elif call.data == "olympiads_mathematics":
        keyboard = types.InlineKeyboardMarkup()
        url_button_1 = types.InlineKeyboardButton(text="Олимпиада школьников «САММАТ»", url="https://abitur71.tsu.tula.ru/olimp-sammat")
        url_button_2 = types.InlineKeyboardButton(text="Региональная on-linе олимпиада школьников по математике «Форсаж»", url="https://ipk-tula.ru/konkursy/forsaj/")
        url_button_3 = types.InlineKeyboardButton(text="Перечневые олимпиады по математике", url="https://postupi.online/olimp-list/?fsubject=8&amp;flevel=5&amp;ysclid=lxk1udd9ez791485874")
        url_button_4 = types.InlineKeyboardButton(text="Олимпиады МАН «Интеллект будущего»", url="https://new.future4you.ru/catalog/contests/")
        url_button_5 = types.InlineKeyboardButton(text="Олимпиада по математике от Учи.ру", url="https://math-olymp.uchi.ru/closed")
        url_button_6 = types.InlineKeyboardButton(text="Всероссийская олимпиада школьников", url="https://siriusolymp.ru/rules")
        url_button_7 = types.InlineKeyboardButton(text="Всероссийская олимпиада по математике «Отличник»", url="https://konkurs-otlichnik.ru/math")
        url_button_8 = types.InlineKeyboardButton(text="Международная олимпиада по математике «Турнир городов»", url="https://dopobr.tularegion.ru/activity/1007/")
        url_button_9 = types.InlineKeyboardButton(text="Олимпиада «Фоксфорд» по математике", url="https://foxford.ru/catalog/olympiads/matematika?utm_referrer=https%3A%2F%2Fya.ru%2F")
        sub_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='mathematics')
        
        keyboard.add(url_button_1)
        keyboard.add(url_button_2)
        keyboard.add(url_button_3)
        keyboard.add(url_button_4)
        keyboard.add(url_button_5)
        keyboard.add(url_button_6)
        keyboard.add(url_button_7)
        keyboard.add(url_button_8)
        keyboard.add(url_button_9)
        keyboard.add(sub_key)
        
        bot.send_message(call.message.chat.id, "Отлично! Обязательно пробуй свои силы! Могу порекомендовать Вам следующие олимпиады по математике:", reply_markup=keyboard)
    elif call.data == "contests_mathematics":
        keyboard = types.InlineKeyboardMarkup()
        url_button_1 = types.InlineKeyboardButton(text="Всероссийские конкурсы ССИТ", url="https://konkurs.sertification.org/new_store/mathematics.htm")
        url_button_2 = types.InlineKeyboardButton(text="Всероссийские конкурсы от МАН «Интеллект будущего»", url="https://new.future4you.ru/catalog/12/filter/subject-is-mathematics/apply/")
        url_button_3 = types.InlineKeyboardButton(text="Всероссийский конкурс математиков «Число Пифагора»", url="https://www.stravinsky-competition.ru/math")
        url_button_4 = types.InlineKeyboardButton(text="Международный математический конкурс «Я решаю»", url="https://math.gs-group.com/?ysclid=lxk3udvu21907854723")
        url_button_5 = types.InlineKeyboardButton(text="«Кенгуру» игровой конкурс по математике", url="https://vk.com/ipokenguru")
        sub_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='mathematics')
        
        keyboard.add(url_button_1)
        keyboard.add(url_button_2)
        keyboard.add(url_button_3)
        keyboard.add(url_button_4)
        keyboard.add(url_button_5)
        keyboard.add(sub_key)
        
        bot.send_message(call.message.chat.id, "Отлично! Обязательно пробуй свои силы! Могу порекомендовать Вам следующие конкурсы по математике:", reply_markup=keyboard)
    elif call.data == "camp_mathematics":
        keyboard = types.InlineKeyboardMarkup()
        url_button_1 = types.InlineKeyboardButton(text="«Спецмат» – онлайн кружок по олимпиадной математике", url="https://olimpiada2x2.ru/?utm_source=yandex&amp;utm_channel=search&amp;utm_campaign=new_campaign&amp;utm_term=---autotargeting&amp;yclid=14017794073498746879")
        url_button_2 = types.InlineKeyboardButton(text="Областной профильный лагерь «Летняя многопрофильная школа»", url="https://тоцдод.рф/областной-профильный-лагерь-лмш/?ysclid=lxiwknjwbj870392740")
        url_button_3 = types.InlineKeyboardButton(text="Летние математические лагеря от Т-банка", url="https://journal.tinkoff.ru/list/summer-math-school/")
        url_button_4 = types.InlineKeyboardButton(text="Летние математические лагеря от СовКомбанка", url="https://journal.sovcombank.ru/semya/letnie-matematicheskie-lagerya-dlya-detei?ysclid=lxk44iq3mo200400191")
        url_button_5 = types.InlineKeyboardButton(text="Курсы по математике от «Фоксфорд»", url="https://foxford.ru/catalog/courses/matematika")
        url_button_6 = types.InlineKeyboardButton(text="Практикум по математике от Stepik", url="https://stepik.org/catalog/6")
        url_button_7 = types.InlineKeyboardButton(text="Курсы подготовки к ОГЭ по математике", url="https://skysmart.ru/courses/oge/matematika")
        url_button_8 = types.InlineKeyboardButton(text="Подготовка к ЕГЭ по математике", url="https://stepik.org/course/103419/promo")
        sub_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='mathematics')
        
        keyboard.add(url_button_1)
        keyboard.add(url_button_2)
        keyboard.add(url_button_3)
        keyboard.add(url_button_4)
        keyboard.add(url_button_5)
        keyboard.add(url_button_6)
        keyboard.add(url_button_7)
        keyboard.add(url_button_8)
        keyboard.add(sub_key)
        
        bot.send_message(call.message.chat.id, "Отлично! Обязательно пробуй свои силы! Могу порекомендовать Вам следующие курсы и профильные лагеря по математике:", reply_markup=keyboard)
    elif call.data == "olympiads_biology":
        keyboard = types.InlineKeyboardMarkup()
        url_button_1 = types.InlineKeyboardButton(text="Всероссийская Сеченовская олимпиада школьников", url="https://www.sechenov.ru/univers/structure/facultie/dovuz/olimpiady/")
        url_button_2 = types.InlineKeyboardButton(text="Всероссийская олимпиада школьников", url="https://vserosolimp.edsoo.ru/")
        url_button_3 = types.InlineKeyboardButton(text="Пироговская олимпиада для школьников по химии и биологии", url="https://rsmu.ru/academics/for-school-students/pirogov-olimpiada/")
        url_button_4 = types.InlineKeyboardButton(text="Перечневые олимпиады по биологии", url="https://postupi.online/olimp-list/?fsubject=2&amp;flevel=5&amp;ysclid=lxk4uh95yc226771947")
        url_button_5 = types.InlineKeyboardButton(text="Перечневые олимпиады по химии", url="https://postupi.online/olimp-list/?fsubject=9&amp;flevel=5&amp;ysclid=lxk4vm1djg107366285")
        url_button_6 = types.InlineKeyboardButton(text="Олимпиады по химии «Фоксфорд»", url="https://foxford.ru/catalog/olympiads/himiya")
        url_button_7 = types.InlineKeyboardButton(text="Международная проектная олимпиада по химии", url="https://chemolymp.ru/?ysclid=lxk524fdns398688400")
        url_button_8 = types.InlineKeyboardButton(text="Международная биологическая олимпиада", url="https://olimpiada.ru/activity/136")
        sub_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='biology')
        
        keyboard.add(url_button_1)
        keyboard.add(url_button_2)
        keyboard.add(url_button_3)
        keyboard.add(url_button_4)
        keyboard.add(url_button_5)
        keyboard.add(url_button_6)
        keyboard.add(url_button_7)
        keyboard.add(url_button_8)
        keyboard.add(sub_key)
        
        bot.send_message(call.message.chat.id, "Отлично! Обязательно пробуй свои силы! Могу порекомендовать Вам следующие олимпиады по биологии и химии:", reply_markup=keyboard)
    elif call.data == "contests_biology":
        keyboard = types.InlineKeyboardMarkup()
        url_button_1 = types.InlineKeyboardButton(text="Детский научный конкурс Фонда Андрея Мельниченко", url="https://dnk.aimfond.ru/")
        url_button_2 = types.InlineKeyboardButton(text="Всероссийские конкурсы по биологии от МАН «Интеллект будущего»", url="https://future4you.ru/index.php?option=com_content&amp;view=article&amp;id=2209&amp;Itemid=1284")
        url_button_3 = types.InlineKeyboardButton(text="Всероссийские конкурсы по химии от МАН «Интеллект будущего»", url="https://future4you.ru/index.php?option=com_content&amp;view=article&amp;id=2220&amp;Itemid=1293")
        url_button_4 = types.InlineKeyboardButton(text="Конкурс исследовательских и проектных работ школьников по биологии «Высший пилотаж»", url="https://olymp.hse.ru/projects/biology-avangard")
        url_button_5 = types.InlineKeyboardButton(text="Конкурс исследовательских и проектных работ школьников по химии «Высший пилотаж»", url="https://olymp.hse.ru/projects/chemistry-avangard?ysclid=lxk5e23srz586338068")
        url_button_6 = types.InlineKeyboardButton(text="Всероссийские сертифицированные конкурсы ССИТ", url="https://konkurs.sertification.org/new_store/2024-25/himik_i_letom_himik_2024/index.php")
        url_button_7 = types.InlineKeyboardButton(text="Международный конкурс проектов в области биологических, химических и медицинских наук", url="http://students.interclover.ru/medical/biochem.html")
        sub_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='biology')
        
        keyboard.add(url_button_1)
        keyboard.add(url_button_2)
        keyboard.add(url_button_3)
        keyboard.add(url_button_4)
        keyboard.add(url_button_5)
        keyboard.add(url_button_6)
        keyboard.add(url_button_7)
        keyboard.add(sub_key)
        
        bot.send_message(call.message.chat.id, "Отлично! Обязательно пробуй свои силы! Могу порекомендовать Вам следующие конкурсы по биологии и химии:", reply_markup=keyboard)
    elif call.data == "camp_biology":
        keyboard = types.InlineKeyboardMarkup()
        url_button_1 = types.InlineKeyboardButton(text="Летние олимпиадные школы Фонда Андрея Мельниченко", url="https://aimfond.ru/proekty/letnie-olimpiadnye-shkoly-fonda-andreya-melnichenko?ysclid=lxk57ahkr2353372972")
        url_button_2 = types.InlineKeyboardButton(text="Областной профильный лагерь «Летняя многопрофильная школа»", url="https://тоцдод.рф/областной-профильный-лагерь-лмш/?ysclid=lxiwknjwbj870392740")
        url_button_3 = types.InlineKeyboardButton(text="Химико-биологические выездные школы", url="https://kidsincamp.ru/camp/himiya-shkola?ysclid=lxk5lagxrh393107076")
        url_button_4 = types.InlineKeyboardButton(text="Научный лагерь МГУ", url="https://slon-i-giraf.ru/lager-mgu")
        url_button_5 = types.InlineKeyboardButton(text="Бесплатные курсы по биологии, химии и медицине", url="https://obrazoval.ru/course-catalog/professionalnoe/biologiya-himiya-i-meditsina/free")
        url_button_6 = types.InlineKeyboardButton(text="Подготовка к ЕГЭ и олимпиадам по биологии и химии", url="https://education.nsu.ru/getready/")
        url_button_7 = types.InlineKeyboardButton(text="Курсы ЕГЭ по различным предметам", url="https://studarium.ru/kurs")
        sub_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='biology')
        
        keyboard.add(url_button_1)
        keyboard.add(url_button_2)
        keyboard.add(url_button_3)
        keyboard.add(url_button_4)
        keyboard.add(url_button_5)
        keyboard.add(url_button_6)
        keyboard.add(url_button_7)
        keyboard.add(sub_key)
        
        bot.send_message(call.message.chat.id, "Отлично! Обязательно пробуй свои силы! Могу порекомендовать Вам следующие курсы и профильные лагеря по биологии и химии:", reply_markup=keyboard)
    elif call.data == "olympiads_english":
        keyboard = types.InlineKeyboardMarkup()
        url_button_1 = types.InlineKeyboardButton(text="Региональные олимпиады по английскому языку", url="https://ipk-tula.ru/konkursy/")
        url_button_2 = types.InlineKeyboardButton(text="Перечневые олимпиады по английскому языку", url="https://postupi.online/olimp-list/?fsubject=31&amp;flevel=5")
        url_button_3 = types.InlineKeyboardButton(text="Всероссийская Олимпиада по английскому языку «Английский язык для глобального прогресса»", url="https://linguastudies.misis.ru/olimpiada-2024/")
        url_button_4 = types.InlineKeyboardButton(text="Всероссийская олимпиада школьников", url="https://vserosolimp.edsoo.ru/")
        url_button_5 = types.InlineKeyboardButton(text="Олимпиады по английскому языку на Учи.Ру", url="https://english.uchi.ru/")
        url_button_6 = types.InlineKeyboardButton(text="Всероссийская олимпиада по английскому языку «Фоксфорд»", url="https://olymp.foxford.ru/?utm_medium=gr&amp;utm_source=roiv&amp;utm_campaign=gr_all_all_olymp2023")
        url_button_7 = types.InlineKeyboardButton(text="Олимпиада школьников по английскому языку «Высшая проба»", url="https://olymp.hse.ru/mmo/lang")
        url_button_8 = types.InlineKeyboardButton(text="Открытая российская интернет олимпиада по английскому языку", url="https://metaschool.ru/internet-olympiada.php?subjectId=3")
        sub_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='english')
        
        keyboard.add(url_button_1)
        keyboard.add(url_button_2)
        keyboard.add(url_button_3)
        keyboard.add(url_button_4)
        keyboard.add(url_button_5)
        keyboard.add(url_button_6)
        keyboard.add(url_button_7)
        keyboard.add(url_button_8)
        keyboard.add(sub_key)
        
        bot.send_message(call.message.chat.id, "Отлично! Обязательно пробуй свои силы! Могу порекомендовать Вам следующие олимпиады по английскому языку:", reply_markup=keyboard)
    elif call.data == "contests_english":
        keyboard = types.InlineKeyboardMarkup()
        url_button_1 = types.InlineKeyboardButton(text="Конкурс МГИМО для школьников по английскому языку «Хочу стать международником»", url="https://eng-contest.mgimo.ru/")
        url_button_2 = types.InlineKeyboardButton(text="Конкурс по английскому языку от МАН «Интеллект будущего»", url="https://new.future4you.ru/catalog/contests/")
        url_button_3 = types.InlineKeyboardButton(text="Дистанционные конкурсы Англиус", url="https://anglius.ru/?utm_referrer=https%3A%2F%2Fya.ru%2F")
        url_button_4 = types.InlineKeyboardButton(text="Всероссийский конкурс по английскому языку Junior Jack", url="https://vk.com/jjkonkurs?ysclid=lxke3gu3mj57764888")
        url_button_5 = types.InlineKeyboardButton(text="Конкурсы по английскому языку", url="https://welcome-test.ru/?past=1&amp;ysclid=lxke5nlwme949179467")
        sub_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='english')
        
        keyboard.add(url_button_1)
        keyboard.add(url_button_2)
        keyboard.add(url_button_3)
        keyboard.add(url_button_4)
        keyboard.add(url_button_5)
        keyboard.add(sub_key)
        
        bot.send_message(call.message.chat.id, "Отлично! Обязательно пробуй свои силы! Могу порекомендовать Вам следующие конкурсы по английскому языку:", reply_markup=keyboard)
    elif call.data == "camp_english":
        keyboard = types.InlineKeyboardMarkup()
        url_button_1 = types.InlineKeyboardButton(text="Онлайн – школа английского языка", url="https://lingvita.ru/?yclid=13775091213495697407")
        url_button_2 = types.InlineKeyboardButton(text="Профильные детские лагеря России по английскому языку", url="https://incamp.ru/camps/russia/profile/english/?ysclid=lxke7g0kiq557643104")
        url_button_3 = types.InlineKeyboardButton(text="Областной профильный лагерь «Летняя многопрофильная школа»", url="https://тоцдод.рф/областной-профильный-лагерь-лмш/?ysclid=lxiwknjwbj870392740")
        url_button_4 = types.InlineKeyboardButton(text="Лингвистический лагерь «Adventure time»", url="https://dialect.online/holidays/adventure-time/?ysclid=lxkeagxoi9913264776")
        url_button_5 = types.InlineKeyboardButton(text="Топ 10 бесплатных сайтов для изучения английского языка (бесплатно)", url="https://top10english.ru/learn/anglijskij-dlya-detej-besplatno/")
        url_button_6 = types.InlineKeyboardButton(text="Онлайн – школа Skysmart", url="https://skysmart.ru/lessons/angliyskiy-yazyk")
        url_button_7 = types.InlineKeyboardButton(text="Изучение английского самостоятельно онлайн", url="https://www.gamestolearnenglish.com/")
        url_button_8 = types.InlineKeyboardButton(text="Изучение иностранных языков бесплатно", url="https://www.duolingo.com/")
        sub_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='english')
        
        keyboard.add(url_button_1)
        keyboard.add(url_button_2)
        keyboard.add(url_button_3)
        keyboard.add(url_button_4)
        keyboard.add(url_button_5)
        keyboard.add(url_button_6)
        keyboard.add(url_button_7)
        keyboard.add(url_button_8)
        keyboard.add(sub_key)
        
        bot.send_message(call.message.chat.id, "Отлично! Обязательно пробуй свои силы! Могу порекомендовать Вам следующие курсы и профильные лагеря по английскому языку:", reply_markup=keyboard)
    elif call.data == "olympiads_russian":
        keyboard = types.InlineKeyboardMarkup()
        url_button_1 = types.InlineKeyboardButton(text="Перечневые олимпиады по русскому языку", url="https://postupi.online/olimp-list/?fsubject=29&amp;flevel=5&amp;ysclid=lxlfzyik4x730870509&amp;utm_source=ya.ru&amp;utm_medium=referral&amp;utm_campaign=ya.ru&amp;utm_referrer=ya.ru")
        url_button_2 = types.InlineKeyboardButton(text="Перечневые олимпиады по литературе", url="https://postupi.online/olimp-list/?fsubject=28&amp;flevel=5&amp;ysclid=lxlg1kz0mn554743571&amp;utm_source=ya.ru&amp;utm_medium=referral&amp;utm_campaign=ya.ru&amp;utm_referrer=ya.ru")
        url_button_3 = types.InlineKeyboardButton(text="Всероссийская олимпиада школьников", url="https://vserosolimp.edsoo.ru/")
        url_button_4 = types.InlineKeyboardButton(text="Профильная олимпиада школьников по русскому языку и литературе", url="https://olimpiada.eduprosvet.ru/fakurl/")
        url_button_5 = types.InlineKeyboardButton(text="Международные олимпиады школьников по русскому языку и литературе", url="https://www.minobr.org/olympiads?predmet_id=8&amp;ysclid=lxlg8cd8uf331742813")
        url_button_6 = types.InlineKeyboardButton(text="Телевизионная олимпиада «Умники и умницы»", url="https://abiturient.mgimo.ru/olimpiady/umniki?utm_source=ya.ru&amp;utm_medium=referral&amp;utm_campaign=ya.ru&amp;utm_referrer=ya.ru")
        url_button_7 = types.InlineKeyboardButton(text="Толстовская олимпиада школьников", url="https://olymp.tsput.ru/lp/")
        sub_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='russian')
        
        keyboard.add(url_button_1)
        keyboard.add(url_button_2)
        keyboard.add(url_button_3)
        keyboard.add(url_button_4)
        keyboard.add(url_button_5)
        keyboard.add(url_button_6)
        keyboard.add(url_button_7)
        keyboard.add(sub_key)
        
        bot.send_message(call.message.chat.id, "Отлично! Обязательно пробуй свои силы! Могу порекомендовать Вам следующие олимпиады по русскому языку и литературе:", reply_markup=keyboard)
    elif call.data == "contests_russian":
        keyboard = types.InlineKeyboardMarkup()
        url_button_1 = types.InlineKeyboardButton(text="Всероссийский конкурс сочинений (муниципальный, региональный, всероссийский этап) «Без срока давности»", url="https://ipk-tula.ru/konkursy/bez_sroka_davnosti/")
        url_button_2 = types.InlineKeyboardButton(text="Областной конкурс «У них в судьбе была война»", url="https://тоцдод.рф/мероприятия-социально-педагогическо/областной-конкурс-эссе-у-них-в-судьбе/")
        url_button_3 = types.InlineKeyboardButton(text="Региональный конкурс чтецов «Защитников Родины славим!»", url="https://тоцдод.рф/мероприятия-социально-педагогическо/региональный-конкурс-чтецов-защитн/")
        url_button_4 = types.InlineKeyboardButton(text="Все конкурсы по различной направленности, которые проводятся в Тульской области вы можете найти на данном сайте, раздел «Мероприятия»", url="https://тоцдод.рф/организация-образовательного-процес/")
        url_button_5 = types.InlineKeyboardButton(text="Международный конкурс юных чтецов «Живая классика»", url="https://youngreaders.ru/?ysclid=lxlgswp7oi929906352")
        url_button_6 = types.InlineKeyboardButton(text="Всероссийские конкурсы социально – гуманитарной направленности", url="https://тоцдод.рф/всероссийские-конкурсы-2022-2/социально-гуманитарная-направленнос/")
        sub_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='russian')
        
        keyboard.add(url_button_1)
        keyboard.add(url_button_2)
        keyboard.add(url_button_3)
        keyboard.add(url_button_4)
        keyboard.add(url_button_5)
        keyboard.add(url_button_6)
        keyboard.add(sub_key)
        
        bot.send_message(call.message.chat.id, "Отлично! Обязательно пробуй свои силы! Могу порекомендовать Вам следующие конкурсы по русскому языку и литературе:", reply_markup=keyboard)
    elif call.data == "camp_russian":
        keyboard = types.InlineKeyboardMarkup()
        url_button_1 = types.InlineKeyboardButton(text="Онлайн – курс по русскому языку (бесплатно)", url="https://www.tutoronline.ru/kursy-russkogo-jazyka/besplatnyj-shkolnyj-kurs-po-russkomu")
        url_button_2 = types.InlineKeyboardButton(text="Уроки русского языка (онлайн)", url="https://skysmart.ru/onlajn-uroki-po-russkomu-yazyku")
        url_button_3 = types.InlineKeyboardButton(text="Бесплатные интерактивные спецкурсы", url="https://foxford.ru/levels/middle")
        url_button_4 = types.InlineKeyboardButton(text="Летняя выездная школа по олимпиадной литературе", url="https://kidsincamp.ru/camp/letnij-literaturnyj-lager")
        url_button_5 = types.InlineKeyboardButton(text="Профильные детские лагеря с изучением русского языка", url="https://mycamps.ru/camps/profilnyj/rossiya/russkij/")
        url_button_6 = types.InlineKeyboardButton(text="Профильная смена Сириус «Литературное творчество»", url="https://sochisirius.ru/obuchenie/literature")
        url_button_7 = types.InlineKeyboardButton(text="Областной профильный лагерь «Летняя многопрофильная школа»", url="https://тоцдод.рф/областной-профильный-лагерь-лмш/?ysclid=lxiwknjwbj870392740")
        sub_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='russian')
        
        keyboard.add(url_button_1)
        keyboard.add(url_button_2)
        keyboard.add(url_button_3)
        keyboard.add(url_button_4)
        keyboard.add(url_button_5)
        keyboard.add(url_button_6)
        keyboard.add(url_button_7)
        keyboard.add(sub_key)
        
        bot.send_message(call.message.chat.id, "Отлично! Обязательно пробуй свои силы! Могу порекомендовать Вам следующие курсы и профильные лагеря по русскому языку и литературе:", reply_markup=keyboard)
    elif call.data == "olympiads_history":
        keyboard = types.InlineKeyboardMarkup()
        url_button_1 = types.InlineKeyboardButton(text="Перечневые олимпиады по обществознанию", url="https://postupi.online/olimp-list/ege-istoriya/?fsubject=10&amp;flevel=5&amp;ysclid=lxlhmuy3k9441484983&amp;utm_source=ya.ru&amp;utm_medium=referral&amp;utm_campaign=ya.ru&amp;utm_referrer=ya.ru")
        url_button_2 = types.InlineKeyboardButton(text="Перечневые олимпиады по истории", url="https://postupi.online/olimp-list/?fsubject=26&amp;flevel=5&amp;utm_source=ya.ru&amp;utm_medium=referral&amp;utm_campaign=ya.ru&amp;utm_referrer=ya.ru")
        url_button_3 = types.InlineKeyboardButton(text="Перечневые олимпиады по праву", url="https://postupi.online/olimp-list/?fsubject=12&amp;flevel=5&amp;ysclid=lxlhv5wb5f150916226&amp;utm_source=ya.ru&amp;utm_medium=referral&amp;utm_campaign=ya.ru&amp;utm_referrer=ya.ru")
        url_button_4 = types.InlineKeyboardButton(text="Всероссийская олимпиада школьников", url="https://vserosolimp.edsoo.ru/")
        url_button_5 = types.InlineKeyboardButton(text="71 олимпиада по обществознанию", url="https://olimpiada.ru/activities?subject%5B9%5D=on&amp;type=any")
        url_button_6 = types.InlineKeyboardButton(text="Международные олимпиады", url="https://www.minobr.org/olympiads?predmet_id=5")
        url_button_7 = types.InlineKeyboardButton(text="Толстовская олимпиада школьников", url="https://www.minobr.org/olympiads?predmet_id=5")
        sub_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='history')
        
        keyboard.add(url_button_1)
        keyboard.add(url_button_2)
        keyboard.add(url_button_3)
        keyboard.add(url_button_4)
        keyboard.add(url_button_5)
        keyboard.add(url_button_6)
        keyboard.add(url_button_7)
        keyboard.add(sub_key)
        
        bot.send_message(call.message.chat.id, "Отлично! Обязательно пробуй свои силы! Могу порекомендовать Вам следующие олимпиады по истории, обществознанию, праву:", reply_markup=keyboard)
    elif call.data == "contests_history":
        keyboard = types.InlineKeyboardMarkup()
        url_button_1 = types.InlineKeyboardButton(text="Все конкурсы по различной направленности, которые проводятся в Тульской области, вы можете найти на данном сайте, раздел «Мероприятия»", url="https://тоцдод.рф/организация-образовательного-процес/")
        url_button_2 = types.InlineKeyboardButton(text="Всероссийские конкурсы социально – гуманитарной направленности", url="https://тоцдод.рф/всероссийские-конкурсы-2022-2/социально-гуманитарная-направленнос/")
        url_button_3 = types.InlineKeyboardButton(text="Конкурсы, проводимые Российским историческим обществом", url="https://historyrussia.org/proekty/zavershennye-konkursy.html?ysclid=lxlkj51iie409763998")
        url_button_4 = types.InlineKeyboardButton(text="Всероссийская онлайн-викторина «Знаток права»", url="https://centreinstein.ru/konkurs/victorina/school/s13/")
        url_button_5 = types.InlineKeyboardButton(text="Конкурсы от МАН «Интеллект будущего»", url="https://future4you.ru/%7C?ysclid=lxlkr8862c59351088")
        sub_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='history')
        
        keyboard.add(url_button_1)
        keyboard.add(url_button_2)
        keyboard.add(url_button_3)
        keyboard.add(url_button_4)
        keyboard.add(url_button_5)
        keyboard.add(sub_key)
        
        bot.send_message(call.message.chat.id, "Отлично! Обязательно пробуй свои силы! Могу порекомендовать Вам следующие конкурсы по истории, обществознанию, праву:", reply_markup=keyboard)
    elif call.data == "camp_history":
        keyboard = types.InlineKeyboardMarkup()
        url_button_1 = types.InlineKeyboardButton(text="Онлайн - курсы по обществознанию", url="https://project.lektorium.tv/social-school#courses")
        url_button_2 = types.InlineKeyboardButton(text="Исторический кружок для школьников", url="https://igoto.su/istoriya-i-obshchestvoznanie")
        url_button_3 = types.InlineKeyboardButton(text="Курс углубленного изучения обществознания (бесплатно)", url="https://stepik.org/course/83362/promo")
        url_button_4 = types.InlineKeyboardButton(text="Курсы по истории от Фоксфорда", url="https://foxford.ru/catalog/courses/istoriya/9-klass?utm_referrer=https%3A%2F%2Fya.ru%2F")
        url_button_5 = types.InlineKeyboardButton(text="Летняя выездная школа по олимпиадному обществознанию", url="https://kidsincamp.ru/camp/obschestvoznanie?ysclid=lxlkyzsu8i608284991")
        url_button_6 = types.InlineKeyboardButton(text="Летняя школа АПО по обществознанию", url="https://апо.рф/курсы/летняя-школа-апо-по-обществознанию/")
        url_button_7 = types.InlineKeyboardButton(text="Летняя школа социально-гуманитарных наук МГИМО", url="https://incamp.ru/camp/letnyaya-shkola-sotsialno-guma-3364/")
        url_button_8 = types.InlineKeyboardButton(text="Областной профильный лагерь «Летняя многопрофильная школа»", url="https://тоцдод.рф/областной-профильный-лагерь-лмш/?ysclid=lxiwknjwbj870392740")
        sub_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='history')
        
        keyboard.add(url_button_1)
        keyboard.add(url_button_2)
        keyboard.add(url_button_3)
        keyboard.add(url_button_4)
        keyboard.add(url_button_5)
        keyboard.add(url_button_6)
        keyboard.add(url_button_7)
        keyboard.add(url_button_8)
        keyboard.add(sub_key)
        
        bot.send_message(call.message.chat.id, "Отлично! Обязательно пробуй свои силы! Могу порекомендовать Вам следующие курсы и профильные лагеря по истории, обществознанию, праву:", reply_markup=keyboard)
    elif call.data == "olympiads_art":
        keyboard = types.InlineKeyboardMarkup()
        url_button_1 = types.InlineKeyboardButton(text="Перечневые олимпиады по искусству, творчеству", url="https://postupi.online/olimp-list/?fsubject=43&amp;flevel=5&amp;ysclid=lxll5memo831060130&amp;utm_source=ya.ru&amp;utm_medium=referral&amp;utm_campaign=ya.ru&amp;utm_referrer=ya.ru")
        url_button_2 = types.InlineKeyboardButton(text="Олимпиада «Культура и искусство»", url="https://olimp.prouniver.ru/")
        url_button_3 = types.InlineKeyboardButton(text="Профильная олимпиада школьников по композиции «Творческий экзамен»", url="https://olimpiada.eduprosvet.ru/izoolimp/")
        url_button_4 = types.InlineKeyboardButton(text="Всероссийская олимпиада школьников", url="https://vserosolimp.edsoo.ru/")
        url_button_5 = types.InlineKeyboardButton(text="Олимпиады по изобразительному искусству для школьников", url="https://a-yda.ru/olimpiady-dlya-shkolnikov/dlya-shkolnikov-po-izobrazitelnomu-iskusstvu/")
        sub_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='art')
        
        keyboard.add(url_button_1)
        keyboard.add(url_button_2)
        keyboard.add(url_button_3)
        keyboard.add(url_button_4)
        keyboard.add(url_button_5)
        keyboard.add(sub_key)
        
        bot.send_message(call.message.chat.id, "Отлично! Обязательно пробуй свои силы! Могу порекомендовать Вам следующие олимпиады по художественному творчеству:", reply_markup=keyboard)
    elif call.data == "contests_art":
        keyboard = types.InlineKeyboardMarkup()
        url_button_1 = types.InlineKeyboardButton(text="Региональные конкурсы художественной направленности", url="https://тоцдод.рф/мероприятия-художественной-направле/")
        url_button_2 = types.InlineKeyboardButton(text="Календарь всероссийских и международных конкурсов", url="https://rfartcenter.ru/sobytiya/konkursy/izo/?ysclid=lxllh1hyz4937919574")
        url_button_3 = types.InlineKeyboardButton(text="Всероссийский конкурс «Большая перемена»", url="https://vsekonkursy.ru/bolshaya-peremena-2024.html")
        url_button_4 = types.InlineKeyboardButton(text="Творческий конкурс «Золотой ЁЖ»", url="https://конкурсы.рф/contests/goldeniozh")
        url_button_5 = types.InlineKeyboardButton(text="Конкурс «Память» от партии «Единая Россия»", url="https://vk.com/wall599436213_2143?ysclid=lxlltw4eib998361265")
        sub_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='art')
        
        keyboard.add(url_button_1)
        keyboard.add(url_button_2)
        keyboard.add(url_button_3)
        keyboard.add(url_button_4)
        keyboard.add(url_button_5)
        keyboard.add(sub_key)
        
        bot.send_message(call.message.chat.id, "Отлично! Обязательно пробуй свои силы! Могу порекомендовать Вам следующие конкурсы по художественному творчеству:", reply_markup=keyboard)
    elif call.data == "camp_art":
        keyboard = types.InlineKeyboardMarkup()
        url_button_1 = types.InlineKeyboardButton(text="Художественная онлайн – школа", url="https://hudozhka.online/?ysclid=lxlm3jasp4419059946")
        url_button_2 = types.InlineKeyboardButton(text="Онлайн – курс «Я юный художник»", url="https://www.hudozhnik.online/young_artist")
        url_button_3 = types.InlineKeyboardButton(text="Курсы по ИЗО от Фоксфорда", url="https://foxford.ru/catalog/courses/izo?utm_referrer=https%3A%2F%2Fya.ru%2F")
        url_button_4 = types.InlineKeyboardButton(text="Творческий лагерь на базе одной из старейших художественных школ России", url="https://leto-art-shkola.ru/?ysclid=lxlm68l9b288994492")
        url_button_5 = types.InlineKeyboardButton(text="Творческие летние лагеря", url="https://incamp.ru/camps/creative/")
        url_button_6 = types.InlineKeyboardButton(text="Художественные лагеря в Тульской области", url="https://kidsincamp.ru/tulskaya_oblast/hudozhestvennyy?ysclid=lxlm8s8ci6730333277")
        sub_key = types.InlineKeyboardButton(text='Вернуться назад', callback_data='art')
        
        keyboard.add(url_button_1)
        keyboard.add(url_button_2)
        keyboard.add(url_button_3)
        keyboard.add(url_button_4)
        keyboard.add(url_button_5)
        keyboard.add(url_button_6)
        keyboard.add(sub_key)
        
        bot.send_message(call.message.chat.id, "Отлично! Обязательно пробуй свои силы! Могу порекомендовать Вам следующие курсы и профильные лагеря по художественному творчеству:", reply_markup=keyboard)
# Запускаем бота
bot.polling(none_stop=True, interval=0)



